In [8]:
import numpy as np
import pandas as pd

In [9]:
phishing_df=pd.read_excel("D:\\uni stuff\\Semester 8\\DSCi\\lab6_datasets\\dataR2.xlsx")
phishing_df.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [10]:
phishing_df.describe()

Age         BMI     Glucose     Insulin        HOMA      Leptin  \
count  116.000000  116.000000  116.000000  116.000000  116.000000  116.000000   
mean    57.301724   27.582111   97.793103   10.012086    2.694988   26.615080   
std     16.112766    5.020136   22.525162   10.067768    3.642043   19.183294   
min     24.000000   18.370000   60.000000    2.432000    0.467409    4.311000   
25%     45.000000   22.973205   85.750000    4.359250    0.917966   12.313675   
50%     56.000000   27.662416   92.000000    5.924500    1.380939   20.271000   
75%     71.000000   31.241442  102.000000   11.189250    2.857787   37.378300   
max     89.000000   38.578759  201.000000   58.460000   25.050342   90.280000   

       Adiponectin    Resistin        MCP.1  Classification  
count   116.000000  116.000000   116.000000      116.000000  
mean     10.180874   14.725966   534.647000        1.551724  
std       6.843341   12.390646   345.912663        0.499475  
min       1.656020    3.210000    45.843000        1.000000  
25%       5.474283    6.881763   269.978250        1.000000  
50%       8.352692   10.827740   471.322500        2.000000  
75%      11.815970   17.755207   700.085000        2.000000  
max      38.040000   82.100000  1698.440000        2.000000

In [11]:
phishing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             116 non-null    int64  
 1   BMI             116 non-null    float64
 2   Glucose         116 non-null    int64  
 3   Insulin         116 non-null    float64
 4   HOMA            116 non-null    float64
 5   Leptin          116 non-null    float64
 6   Adiponectin     116 non-null    float64
 7   Resistin        116 non-null    float64
 8   MCP.1           116 non-null    float64
 9   Classification  116 non-null    int64  
dtypes: float64(7), int64(3)
memory usage: 9.2 KB


In [12]:
phishing_df.isnull().sum()

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

In [13]:
phishing_df.dtypes

Age                 int64
BMI               float64
Glucose             int64
Insulin           float64
HOMA              float64
Leptin            float64
Adiponectin       float64
Resistin          float64
MCP.1             float64
Classification      int64
dtype: object

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
y = np.asarray(phishing_df[['Classification']])
b=(list(phishing_df))
#print(b[:-1])
X = np.asarray(phishing_df[b[:-1]])

In [16]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

## 10 Fold cv
### DT using gini (without pruning)

In [17]:
dtree_phising1=DecisionTreeClassifier(criterion="gini")

In [18]:
scores = cross_val_score(dtree_phising1, X, y, cv=10)

In [19]:
scores

array([0.66666667, 0.66666667, 0.5       , 0.83333333, 0.83333333,
       0.75      , 0.63636364, 0.81818182, 0.54545455, 0.45454545])

In [20]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.6705 accuracy with a standard deviation of 0.13


### DT using gini (with pruning)

In [21]:
dtree_phising2=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)

In [22]:
scoresphising2 = cross_val_score(dtree_phising1, X, y, cv=10)


In [23]:
scoresphising2

array([0.66666667, 0.75      , 0.66666667, 0.83333333, 0.83333333,
       0.75      , 0.63636364, 0.81818182, 0.54545455, 0.54545455])

In [24]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising2.mean(), scoresphising2.std()))

0.7045 accuracy with a standard deviation of 0.10


### DT using entropy (without pruning)

In [25]:
dtree_phising2=DecisionTreeClassifier(criterion="entropy")

In [26]:
scoresphising3 = cross_val_score(dtree_phising2, X, y, cv=10)

In [27]:
scoresphising3

array([0.75      , 0.66666667, 0.66666667, 0.75      , 0.91666667,
       0.83333333, 0.90909091, 0.27272727, 0.63636364, 0.72727273])

In [28]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising3.mean(), scoresphising3.std()))

0.7129 accuracy with a standard deviation of 0.17


### DT using entropy (with pruning)

In [29]:
dtree_phising3=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
scoresphising4 = cross_val_score(dtree_phising3, X, y, cv=10)
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising4.mean(), scoresphising4.std()))

0.6795 accuracy with a standard deviation of 0.16


## 70% holdout
### DT using gini (without pruning)

In [30]:
from sklearn.metrics import accuracy_score
scoresphising5=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising5.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising5).mean(), np.std(np.array(scoresphising5))))


0.7643 accuracy with a standard deviation of 0.0148


In [31]:
scoresphising6=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising6.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising6).mean(), np.std(np.array(scoresphising6))))

0.7629 accuracy with a standard deviation of 0.0130930734


In [32]:
scoresphising7=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising7.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising7).mean(), np.std(np.array(scoresphising7))))

0.7577 accuracy with a standard deviation of 0.0143


In [33]:
scoresphising8=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising8.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising8).mean(), np.std(np.array(scoresphising8))))

0.7597 accuracy with a standard deviation of 0.0140523801
