In [11]:
import numpy as np
import pandas as pd

In [12]:
phishing_df=pd.read_csv("D:\\uni stuff\\Semester 8\\DSCi\\lab6_datasets\\sobar-72.csv")
phishing_df.head()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                   10               13                       12   
1                   10               11                       11   
2                   10               15                        3   
3                   10               11                       10   
4                    8               11                        7   

   intention_aggregation  intention_commitment  attitude_consistency  \
0                      4                     7                     9   
1                     10                    14                     7   
2                      2                    14                     8   
3                     10                    15                     7   
4                      8                    10                     7   

   attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
0                    10                       1                 8   
1                     7                       5                 5   
2                    10                       1                 4   
3                     7                       1                 5   
4                     8                       1                 5   

   perception_vulnerability  perception_severity  motivation_strength  \
0                         7                    3                   14   
1                         4                    2                   15   
2                         7                    2                    7   
3                         4                    2                   15   
4                         3                    2                   15   

   motivation_willingness  socialSupport_emotionality  \
0                       8                           5   
1                      13                           7   
2                       3                           3   
3                      13                           7   
4                       5                           3   

   socialSupport_appreciation  socialSupport_instrumental  \
0                           7                          12   
1                           6                           5   
2                           6                          11   
3                           4                           4   
4                           6                          12   

   empowerment_knowledge  empowerment_abilities  empowerment_desires  \
0                     12                     11                    8   
1                      5                      4                    4   
2                      3                      3                   15   
3                      4                      4                    4   
4                      5                      4                    7   

   ca_cervix  
0          1  
1          1  
2          1  
3          1  
4          1

In [13]:
phishing_df.describe()

behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
count            72.000000        72.000000                72.000000   
mean              9.666667        12.791667                11.083333   
std               1.186782         2.361293                 3.033847   
min               2.000000         3.000000                 3.000000   
25%              10.000000        11.000000                 9.000000   
50%              10.000000        13.000000                11.000000   
75%              10.000000        15.000000                14.000000   
max              10.000000        15.000000                15.000000   

       intention_aggregation  intention_commitment  attitude_consistency  \
count              72.000000             72.000000             72.000000   
mean                7.902778             13.347222              7.180556   
std                 2.738148              2.374511              1.522844   
min                 2.000000              6.000000              2.000000   
25%                 6.000000             11.000000              6.000000   
50%                10.000000             15.000000              7.000000   
75%                10.000000             15.000000              8.000000   
max                10.000000             15.000000             10.000000   

       attitude_spontaneity  norm_significantPerson  norm_fulfillment  \
count             72.000000               72.000000         72.000000   
mean               8.611111                3.125000          8.486111   
std                1.515698                1.845722          4.907577   
min                4.000000                1.000000          3.000000   
25%                8.000000                1.000000          3.000000   
50%                9.000000                3.000000          7.000000   
75%               10.000000                5.000000         14.000000   
max               10.000000                5.000000         15.000000   

       perception_vulnerability  perception_severity  motivation_strength  \
count                 72.000000            72.000000            72.000000   
mean                   8.513889             5.388889            12.652778   
std                    4.275686             3.400727             3.207209   
min                    3.000000             2.000000             3.000000   
25%                    5.000000             2.000000            11.000000   
50%                    8.000000             4.000000            14.000000   
75%                   13.000000             9.000000            15.000000   
max                   15.000000            10.000000            15.000000   

       motivation_willingness  socialSupport_emotionality  \
count               72.000000                   72.000000   
mean                 9.694444                    8.097222   
std                  4.130406                    4.243171   
min                  3.000000                    3.000000   
25%                  7.000000                    3.000000   
50%                 11.000000                    9.000000   
75%                 13.000000                   11.250000   
max                 15.000000                   15.000000   

       socialSupport_appreciation  socialSupport_instrumental  \
count                   72.000000                   72.000000   
mean                     6.166667                   10.375000   
std                      2.897303                    4.316485   
min                      2.000000                    3.000000   
25%                      3.750000                    6.750000   
50%                      6.500000                   12.000000   
75%                      9.000000                   14.250000   
max                     10.000000                   15.000000   

       empowerment_knowledge  empowerment_abilities  empowerment_desires  \
count              72.000000              72.000000            72.000000   
mean               10.541667     

In [14]:
phishing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   behavior_sexualRisk         72 non-null     int64
 1   behavior_eating             72 non-null     int64
 2   behavior_personalHygine     72 non-null     int64
 3   intention_aggregation       72 non-null     int64
 4   intention_commitment        72 non-null     int64
 5   attitude_consistency        72 non-null     int64
 6   attitude_spontaneity        72 non-null     int64
 7   norm_significantPerson      72 non-null     int64
 8   norm_fulfillment            72 non-null     int64
 9   perception_vulnerability    72 non-null     int64
 10  perception_severity         72 non-null     int64
 11  motivation_strength         72 non-null     int64
 12  motivation_willingness      72 non-null     int64
 13  socialSupport_emotionality  72 non-null     int64
 14  socialSuppor

In [15]:
phishing_df.isnull().sum()

behavior_sexualRisk           0
behavior_eating               0
behavior_personalHygine       0
intention_aggregation         0
intention_commitment          0
attitude_consistency          0
attitude_spontaneity          0
norm_significantPerson        0
norm_fulfillment              0
perception_vulnerability      0
perception_severity           0
motivation_strength           0
motivation_willingness        0
socialSupport_emotionality    0
socialSupport_appreciation    0
socialSupport_instrumental    0
empowerment_knowledge         0
empowerment_abilities         0
empowerment_desires           0
ca_cervix                     0
dtype: int64

In [16]:
phishing_df.dtypes

behavior_sexualRisk           int64
behavior_eating               int64
behavior_personalHygine       int64
intention_aggregation         int64
intention_commitment          int64
attitude_consistency          int64
attitude_spontaneity          int64
norm_significantPerson        int64
norm_fulfillment              int64
perception_vulnerability      int64
perception_severity           int64
motivation_strength           int64
motivation_willingness        int64
socialSupport_emotionality    int64
socialSupport_appreciation    int64
socialSupport_instrumental    int64
empowerment_knowledge         int64
empowerment_abilities         int64
empowerment_desires           int64
ca_cervix                     int64
dtype: object

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
y = np.asarray(phishing_df[['ca_cervix']])
b=(list(phishing_df))
#print(b[:-1])
X = np.asarray(phishing_df[b[:-1]])

In [19]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

## 10 Fold cv
### DT using gini (without pruning)

In [20]:
dtree_phising1=DecisionTreeClassifier(criterion="gini")

In [21]:
scores = cross_val_score(dtree_phising1, X, y, cv=10)

In [22]:
scores

array([0.875     , 0.75      , 1.        , 0.57142857, 1.        ,
       0.71428571, 0.71428571, 1.        , 0.85714286, 0.71428571])

In [23]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.8196 accuracy with a standard deviation of 0.14


### DT using gini (with pruning)

In [24]:
dtree_phising2=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)

In [25]:
scoresphising2 = cross_val_score(dtree_phising1, X, y, cv=10)


In [26]:
scoresphising2

array([0.875     , 0.75      , 0.71428571, 0.57142857, 1.        ,
       0.71428571, 0.71428571, 1.        , 0.85714286, 0.85714286])

In [27]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising2.mean(), scoresphising2.std()))

0.8054 accuracy with a standard deviation of 0.13


### DT using entropy (without pruning)

In [28]:
dtree_phising2=DecisionTreeClassifier(criterion="entropy")

In [29]:
scoresphising3 = cross_val_score(dtree_phising2, X, y, cv=10)

In [30]:
scoresphising3

array([1.        , 0.875     , 0.85714286, 0.28571429, 1.        ,
       0.71428571, 1.        , 1.        , 0.85714286, 0.85714286])

In [31]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising3.mean(), scoresphising3.std()))

0.8446 accuracy with a standard deviation of 0.21


### DT using entropy (with pruning)

In [32]:
dtree_phising3=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
scoresphising4 = cross_val_score(dtree_phising3, X, y, cv=10)
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising4.mean(), scoresphising4.std()))

0.8607 accuracy with a standard deviation of 0.17


## 70% holdout
### DT using gini (without pruning)

In [33]:
from sklearn.metrics import accuracy_score
scoresphising5=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising5.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising5).mean(), np.std(np.array(scoresphising5))))


0.8364 accuracy with a standard deviation of 0.0412


In [34]:
scoresphising6=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising6.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising6).mean(), np.std(np.array(scoresphising6))))

0.8414 accuracy with a standard deviation of 0.0366438070


In [35]:
scoresphising7=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising7.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising7).mean(), np.std(np.array(scoresphising7))))

0.9068 accuracy with a standard deviation of 0.0371


In [36]:
scoresphising8=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising8.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising8).mean(), np.std(np.array(scoresphising8))))

0.9086 accuracy with a standard deviation of 0.0366438070
