In [1]:
import numpy as np
import pandas as pd

In [3]:
phishing_df=pd.read_csv("D:\\uni stuff\\Semester 8\\DSCi\\phishing.arff")
phishing_df.head()

having_IP_Address  URL_Length  Shortining_Service   having_At_Symbol  \
0                 -1           1                   1                  1   
1                  1           1                   1                  1   
2                  1           0                   1                  1   
3                  1           0                   1                  1   
4                  1           0                  -1                  1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1      -1  
1                       1                   1      -1  
2                       0                  -1      -1  
3                      -1                   1      -1  
4                       1                   1       1  

[5 rows x 31 columns]

In [4]:
phishing_df.describe()

having_IP_Address    URL_Length  Shortining_Service   having_At_Symbol  \
count       11055.000000  11055.000000        11055.000000       11055.000000   
mean            0.313795     -0.633198            0.738761           0.700588   
std             0.949534      0.766095            0.673998           0.713598   
min            -1.000000     -1.000000           -1.000000          -1.000000   
25%            -1.000000     -1.000000            1.000000           1.000000   
50%             1.000000     -1.000000            1.000000           1.000000   
75%             1.000000     -1.000000            1.000000           1.000000   
max             1.000000      1.000000            1.000000           1.000000   

       double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  \
count              11055.000000   11055.000000       11055.000000   
mean                   0.741474      -0.734962           0.063953   
std                    0.671011       0.678139           0.817518   
min                   -1.000000      -1.000000          -1.000000   
25%                    1.000000      -1.000000          -1.000000   
50%                    1.000000      -1.000000           0.000000   
75%                    1.000000      -1.000000           1.000000   
max                    1.000000       1.000000           1.000000   

       SSLfinal_State  Domain_registeration_length       Favicon  ...  \
count    11055.000000                 11055.000000  11055.000000  ...   
mean         0.250927                    -0.336771      0.628584  ...   
std          0.911892                     0.941629      0.777777  ...   
min         -1.000000                    -1.000000     -1.000000  ...   
25%         -1.000000                    -1.000000      1.000000  ...   
50%          1.000000                    -1.000000      1.000000  ...   
75%          1.000000                     1.000000      1.000000  ...   
max          1.000000                     1.000000      1.000000  ...   

        popUpWidnow        Iframe  age_of_domain     DNSRecord   web_traffic  \
count  11055.000000  11055.000000   11055.000000  11055.000000  11055.000000   
mean       0.613388      0.816915       0.061239      0.377114      0.287291   
std        0.789818      0.576784       0.998168      0.926209      0.827733   
min       -1.000000     -1.000000      -1.000000     -1.000000     -1.000000   
25%        1.000000      1.000000      -1.000000     -1.000000      0.000000   
50%        1.000000      1.000000       1.000000      1.000000      1.000000   
75%        1.000000      1.000000       1.000000      1.000000      1.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

          Page_Rank  Google_Index  Links_pointing_to_page  Statistical_report  \
count  11055.000000  11055.000000            11055.000000        11055.000000   
mean      -0.483673      0.721574                0.344007            0.719584   
std        0.875289      0.692369                0.569944            0.694437   
min       -1.000000     -1.000000               -1.000000           -1.000000   
25%       -1.000000      1.000000                0.000000            1.000000   
50%       -1.000000      1.000000                0.000000            1.000000   
75%        1.000000      1.000000                1.000000            1.000000   
max        1.000000      1.000000                1.000000            1.000000   

             Result  
count  11055.000000  
mean       0.113885  
std        0.993539  
min       -1.000000  
25%       -1.000000  
50%        1.000000  
75%        1.000000  
max        1.000000  

[8 rows x 31 columns]

In [5]:
phishing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   having_IP_Address            11055 non-null  int64
 1   URL_Length                   11055 non-null  int64
 2   Shortining_Service           11055 non-null  int64
 3    having_At_Symbol            11055 non-null  int64
 4   double_slash_redirecting     11055 non-null  int64
 5   Prefix_Suffix                11055 non-null  int64
 6   having_Sub_Domain            11055 non-null  int64
 7   SSLfinal_State               11055 non-null  int64
 8   Domain_registeration_length  11055 non-null  int64
 9   Favicon                      11055 non-null  int64
 10  port                         11055 non-null  int64
 11  HTTPS_token                  11055 non-null  int64
 12  Request_URL                  11055 non-null  int64
 13  URL_of_Anchor                11055 non-null  i

In [6]:
phishing_df.isnull().sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
 having_At_Symbol              0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result    

In [10]:
phishing_df.dtypes

having_IP_Address              int64
URL_Length                     int64
Shortining_Service             int64
 having_At_Symbol              int64
double_slash_redirecting       int64
Prefix_Suffix                  int64
having_Sub_Domain              int64
SSLfinal_State                 int64
Domain_registeration_length    int64
Favicon                        int64
port                           int64
HTTPS_token                    int64
Request_URL                    int64
URL_of_Anchor                  int64
Links_in_tags                  int64
SFH                            int64
Submitting_to_email            int64
Abnormal_URL                   int64
Redirect                       int64
on_mouseover                   int64
RightClick                     int64
popUpWidnow                    int64
Iframe                         int64
age_of_domain                  int64
DNSRecord                      int64
web_traffic                    int64
Page_Rank                      int64
G

In [12]:
from sklearn.model_selection import train_test_split

In [18]:
y = np.asarray(phishing_df[['Result']])
b=(list(phishing_df))
#print(b[:-1])
X = np.asarray(phishing_df[b[:-1]])

In [16]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

## 10 Fold cv
### DT using gini (without pruning)

In [28]:
dtree_phising1=DecisionTreeClassifier(criterion="gini")

In [29]:
scores = cross_val_score(dtree_phising1, X, y, cv=10)

In [30]:
scores

array([0.98553345, 0.98191682, 0.96925859, 0.98462929, 0.97468354,
       0.96651584, 0.93393665, 0.93303167, 0.94660633, 0.93846154])

In [31]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.9615 accuracy with a standard deviation of 0.02


### DT using gini (with pruning)

In [32]:
dtree_phising2=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)

In [33]:
scoresphising2 = cross_val_score(dtree_phising1, X, y, cv=10)


In [34]:
scoresphising2

array([0.98643761, 0.98282098, 0.96925859, 0.98462929, 0.9755877 ,
       0.96289593, 0.93484163, 0.93122172, 0.94932127, 0.93665158])

In [35]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising2.mean(), scoresphising2.std()))

0.9614 accuracy with a standard deviation of 0.02


### DT using entropy (without pruning)

In [36]:
dtree_phising2=DecisionTreeClassifier(criterion="entropy")

In [37]:
scoresphising3 = cross_val_score(dtree_phising2, X, y, cv=10)

In [38]:
scoresphising3

array([0.98643761, 0.98191682, 0.97016275, 0.98462929, 0.97649186,
       0.96742081, 0.93755656, 0.93393665, 0.94660633, 0.94208145])

In [39]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising3.mean(), scoresphising3.std()))

0.9627 accuracy with a standard deviation of 0.02


### DT using entropy (with pruning)

In [40]:
dtree_phising3=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
scoresphising4 = cross_val_score(dtree_phising3, X, y, cv=10)
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising4.mean(), scoresphising4.std()))

0.9025 accuracy with a standard deviation of 0.01


## 70% holdout
### DT using gini (without pruning)

In [51]:
from sklearn.metrics import accuracy_score
scoresphising5=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising5.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising5).mean(), np.std(np.array(scoresphising5))))


0.9583 accuracy with a standard deviation of 0.0011


In [62]:
scoresphising6=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising6.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising6).mean(), np.std(np.array(scoresphising6))))

0.9002 accuracy with a standard deviation of 0.0000000000


In [56]:
scoresphising7=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising7.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising7).mean(), np.std(np.array(scoresphising7))))

0.9571 accuracy with a standard deviation of 0.0010


In [59]:
scoresphising8=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising8.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising8).mean(), np.std(np.array(scoresphising8))))

0.9002 accuracy with a standard deviation of 0.0000000000
