In [35]:
import numpy as np
import pandas as pd

In [36]:
phishing_df=pd.read_excel("D:\\uni stuff\\Semester 8\\DSCi\\lab6_datasets\\divorce.xlsx")
phishing_df.head()

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr46  \
0     2     2     4     1     0     0     0     0     0      0  ...      2   
1     4     4     4     4     4     0     0     4     4      4  ...      2   
2     2     2     2     2     1     3     2     1     1      2  ...      3   
3     3     2     3     2     3     3     3     3     3      3  ...      2   
4     2     2     1     1     1     1     0     0     0      0  ...      2   

   Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  Class  
0      1      3      3      3      2      3      2      1      1  
1      2      3      4      4      4      4      2      2      1  
2      2      3      1      1      1      2      2      2      1  
3      2      3      3      3      3      2      2      2      1  
4      1      2      3      2      2      2      1      0      1  

[5 rows x 55 columns]

In [37]:
phishing_df.describe()

Atr1        Atr2        Atr3        Atr4        Atr5        Atr6  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000   
mean     1.776471    1.652941    1.764706    1.482353    1.541176    0.747059   
std      1.627257    1.468654    1.415444    1.504327    1.632169    0.904046   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      2.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
75%      3.000000    3.000000    3.000000    3.000000    3.000000    1.000000   
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000   

             Atr7        Atr8        Atr9       Atr10  ...       Atr46  \
count  170.000000  170.000000  170.000000  170.000000  ...  170.000000   
mean     0.494118    1.452941    1.458824    1.576471  ...    2.552941   
std      0.898698    1.546371    1.557976    1.421529  ...    1.371786   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    2.000000   
50%      0.000000    1.000000    1.000000    2.000000  ...    3.000000   
75%      1.000000    3.000000    3.000000    3.000000  ...    4.000000   
max      4.000000    4.000000    4.000000    4.000000  ...    4.000000   

            Atr47       Atr48       Atr49       Atr50       Atr51       Atr52  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000   
mean     2.270588    2.741176    2.382353    2.429412    2.476471    2.517647   
std      1.586841    1.137348    1.511587    1.405090    1.260238    1.476537   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000    2.000000    1.000000    1.000000    2.000000    1.000000   
50%      2.000000    3.000000    3.000000    2.000000    3.000000    3.000000   
75%      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000   
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000   

            Atr53       Atr54       Class  
count  170.000000  170.000000  170.000000  
mean     2.241176    2.011765    0.494118  
std      1.505634    1.667611    0.501442  
min      0.000000    0.000000    0.000000  
25%      1.000000    0.000000    0.000000  
50%      2.000000    2.000000    0.000000  
75%      4.000000    4.000000    1.000000  
max      4.000000    4.000000    1.000000  

[8 rows x 55 columns]

In [38]:
phishing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 55 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Atr1    170 non-null    int64
 1   Atr2    170 non-null    int64
 2   Atr3    170 non-null    int64
 3   Atr4    170 non-null    int64
 4   Atr5    170 non-null    int64
 5   Atr6    170 non-null    int64
 6   Atr7    170 non-null    int64
 7   Atr8    170 non-null    int64
 8   Atr9    170 non-null    int64
 9   Atr10   170 non-null    int64
 10  Atr11   170 non-null    int64
 11  Atr12   170 non-null    int64
 12  Atr13   170 non-null    int64
 13  Atr14   170 non-null    int64
 14  Atr15   170 non-null    int64
 15  Atr16   170 non-null    int64
 16  Atr17   170 non-null    int64
 17  Atr18   170 non-null    int64
 18  Atr19   170 non-null    int64
 19  Atr20   170 non-null    int64
 20  Atr21   170 non-null    int64
 21  Atr22   170 non-null    int64
 22  Atr23   170 non-null    int64
 23  Atr24   170 non

In [39]:
phishing_df.isnull().sum()

Atr1     0
Atr2     0
Atr3     0
Atr4     0
Atr5     0
Atr6     0
Atr7     0
Atr8     0
Atr9     0
Atr10    0
Atr11    0
Atr12    0
Atr13    0
Atr14    0
Atr15    0
Atr16    0
Atr17    0
Atr18    0
Atr19    0
Atr20    0
Atr21    0
Atr22    0
Atr23    0
Atr24    0
Atr25    0
Atr26    0
Atr27    0
Atr28    0
Atr29    0
Atr30    0
Atr31    0
Atr32    0
Atr33    0
Atr34    0
Atr35    0
Atr36    0
Atr37    0
Atr38    0
Atr39    0
Atr40    0
Atr41    0
Atr42    0
Atr43    0
Atr44    0
Atr45    0
Atr46    0
Atr47    0
Atr48    0
Atr49    0
Atr50    0
Atr51    0
Atr52    0
Atr53    0
Atr54    0
Class    0
dtype: int64

In [40]:
phishing_df.dtypes

Atr1     int64
Atr2     int64
Atr3     int64
Atr4     int64
Atr5     int64
Atr6     int64
Atr7     int64
Atr8     int64
Atr9     int64
Atr10    int64
Atr11    int64
Atr12    int64
Atr13    int64
Atr14    int64
Atr15    int64
Atr16    int64
Atr17    int64
Atr18    int64
Atr19    int64
Atr20    int64
Atr21    int64
Atr22    int64
Atr23    int64
Atr24    int64
Atr25    int64
Atr26    int64
Atr27    int64
Atr28    int64
Atr29    int64
Atr30    int64
Atr31    int64
Atr32    int64
Atr33    int64
Atr34    int64
Atr35    int64
Atr36    int64
Atr37    int64
Atr38    int64
Atr39    int64
Atr40    int64
Atr41    int64
Atr42    int64
Atr43    int64
Atr44    int64
Atr45    int64
Atr46    int64
Atr47    int64
Atr48    int64
Atr49    int64
Atr50    int64
Atr51    int64
Atr52    int64
Atr53    int64
Atr54    int64
Class    int64
dtype: object

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
y = np.asarray(phishing_df[['Class']])
b=(list(phishing_df))
#print(b[:-1])
X = np.asarray(phishing_df[b[:-1]])

In [43]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

## 10 Fold cv
### DT using gini (without pruning)

In [44]:
dtree_phising1=DecisionTreeClassifier(criterion="gini")

In [45]:
scores = cross_val_score(dtree_phising1, X, y, cv=10)

In [46]:
scores

array([0.82352941, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.94117647, 1.        , 1.        , 0.94117647])

In [47]:
print("%0.4f accuracy with a standard deviation of %0.4f" % (scores.mean(), scores.std()))

0.9706 accuracy with a standard deviation of 0.0542


### DT using gini (with pruning)

In [48]:
dtree_phising2=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)

In [49]:
scoresphising2 = cross_val_score(dtree_phising1, X, y, cv=10)


In [50]:
scoresphising2

array([0.82352941, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.94117647, 1.        , 1.        , 0.82352941])

In [51]:
print("%0.4f accuracy with a standard deviation of %0.4f" % (scoresphising2.mean(), scoresphising2.std()))

0.9588 accuracy with a standard deviation of 0.0698


### DT using entropy (without pruning)

In [52]:
dtree_phising2=DecisionTreeClassifier(criterion="entropy")

In [53]:
scoresphising3 = cross_val_score(dtree_phising2, X, y, cv=10)

In [54]:
scoresphising3

array([0.82352941, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.94117647, 1.        , 0.94117647, 0.88235294])

In [55]:
print("%0.4f accuracy with a standard deviation of %0.4f" % (scoresphising3.mean(), scoresphising3.std()))

0.9588 accuracy with a standard deviation of 0.0591


### DT using entropy (with pruning)

In [56]:
dtree_phising3=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
scoresphising4 = cross_val_score(dtree_phising3, X, y, cv=10)
print("%0.4f accuracy with a standard deviation of %0.4f" % (scoresphising4.mean(), scoresphising4.std()))

0.9588 accuracy with a standard deviation of 0.0529


## 70% holdout
### DT using gini (without pruning)

In [57]:
from sklearn.metrics import accuracy_score
scoresphising5=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising5.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising5).mean(), np.std(np.array(scoresphising5))))


0.9608 accuracy with a standard deviation of 0.0000


In [58]:
scoresphising6=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising6.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising6).mean(), np.std(np.array(scoresphising6))))

0.9608 accuracy with a standard deviation of 0.0000000000


In [59]:
scoresphising7=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising7.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising7).mean(), np.std(np.array(scoresphising7))))

0.9608 accuracy with a standard deviation of 0.0000


In [60]:
scoresphising8=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising8.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising8).mean(), np.std(np.array(scoresphising8))))

0.9608 accuracy with a standard deviation of 0.0000000000
