In [15]:
import numpy as np
import pandas as pd

In [16]:
phishing_df=pd.read_csv("D:\\uni stuff\\Semester 8\\DSCi\\lab6_datasets\\PhishingData.arff")
phishing_df.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    1           -1               1           -1             -1            1   
1   -1           -1              -1           -1             -1            0   
2    1           -1               0            0             -1            0   
3    1            0               1           -1             -1            0   
4   -1           -1               1           -1              0            0   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           1              1                  0       0  
1           1              1                  1       1  
2          -1              1                  0       1  
3           1              1                  0       0  
4          -1              1                  0       1

In [17]:
phishing_df.describe()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
count  1353.000000  1353.000000     1353.000000  1353.000000    1353.000000   
mean      0.237990    -0.258684        0.327421    -0.223208      -0.025129   
std       0.916389     0.679072        0.822193     0.799682       0.936262   
min      -1.000000    -1.000000       -1.000000    -1.000000      -1.000000   
25%      -1.000000    -1.000000        0.000000    -1.000000      -1.000000   
50%       1.000000     0.000000        1.000000     0.000000       0.000000   
75%       1.000000     0.000000        1.000000     0.000000       1.000000   
max       1.000000     1.000000        1.000000     1.000000       1.000000   

       web_traffic   URL_Length  age_of_domain  having_IP_Address       Result  
count  1353.000000  1353.000000    1353.000000        1353.000000  1353.000000  
mean      0.000000    -0.053215       0.219512           0.114560    -0.113821  
std       0.806776     0.762552       0.975970           0.318608     0.954773  
min      -1.000000    -1.000000      -1.000000           0.000000    -1.000000  
25%      -1.000000    -1.000000      -1.000000           0.000000    -1.000000  
50%       0.000000     0.000000       1.000000           0.000000    -1.000000  
75%       1.000000     1.000000       1.000000           0.000000     1.000000  
max       1.000000     1.000000       1.000000           1.000000     1.000000

In [18]:
phishing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353 entries, 0 to 1352
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SFH                1353 non-null   int64
 1   popUpWidnow        1353 non-null   int64
 2   SSLfinal_State     1353 non-null   int64
 3   Request_URL        1353 non-null   int64
 4   URL_of_Anchor      1353 non-null   int64
 5   web_traffic        1353 non-null   int64
 6   URL_Length         1353 non-null   int64
 7   age_of_domain      1353 non-null   int64
 8   having_IP_Address  1353 non-null   int64
 9   Result             1353 non-null   int64
dtypes: int64(10)
memory usage: 105.8 KB


In [19]:
phishing_df.isnull().sum()

SFH                  0
popUpWidnow          0
SSLfinal_State       0
Request_URL          0
URL_of_Anchor        0
web_traffic          0
URL_Length           0
age_of_domain        0
having_IP_Address    0
Result               0
dtype: int64

In [20]:
phishing_df.dtypes

SFH                  int64
popUpWidnow          int64
SSLfinal_State       int64
Request_URL          int64
URL_of_Anchor        int64
web_traffic          int64
URL_Length           int64
age_of_domain        int64
having_IP_Address    int64
Result               int64
dtype: object

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
y = np.asarray(phishing_df[['Result']])
b=(list(phishing_df))
#print(b[:-1])
X = np.asarray(phishing_df[b[:-1]])

In [23]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

## 10 Fold cv
### DT using gini (without pruning)

In [24]:
dtree_phising1=DecisionTreeClassifier(criterion="gini")

In [25]:
scores = cross_val_score(dtree_phising1, X, y, cv=10)

In [26]:
scores

array([0.88970588, 0.82352941, 0.84558824, 0.91851852, 0.93333333,
       0.86666667, 0.88148148, 0.9037037 , 0.91851852, 0.87407407])

In [42]:
print("%0.4f accuracy with a standard deviation of %0.3f" % (scores.mean(), scores.std()))

0.8855 accuracy with a standard deviation of 0.033


### DT using gini (with pruning)

In [28]:
dtree_phising2=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)

In [29]:
scoresphising2 = cross_val_score(dtree_phising1, X, y, cv=10)


In [30]:
scoresphising2

array([0.89705882, 0.81617647, 0.84558824, 0.9037037 , 0.93333333,
       0.85925926, 0.88148148, 0.88148148, 0.9037037 , 0.85185185])

In [41]:
print("%0.4f accuracy with a standard deviation of %0.3f" % (scoresphising2.mean(), scoresphising2.std()))

0.8774 accuracy with a standard deviation of 0.033


### DT using entropy (without pruning)

In [32]:
dtree_phising2=DecisionTreeClassifier(criterion="entropy")

In [33]:
scoresphising3 = cross_val_score(dtree_phising2, X, y, cv=10)

In [34]:
scoresphising3

array([0.88970588, 0.81617647, 0.86764706, 0.8962963 , 0.92592593,
       0.86666667, 0.88148148, 0.87407407, 0.9037037 , 0.88148148])

In [35]:
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising3.mean(), scoresphising3.std()))

0.8803 accuracy with a standard deviation of 0.03


### DT using entropy (with pruning)

In [36]:
dtree_phising3=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
scoresphising4 = cross_val_score(dtree_phising3, X, y, cv=10)
print("%0.4f accuracy with a standard deviation of %0.2f" % (scoresphising4.mean(), scoresphising4.std()))

0.8589 accuracy with a standard deviation of 0.02


## 70% holdout
### DT using gini (without pruning)

In [37]:
from sklearn.metrics import accuracy_score
scoresphising5=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising5.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising5).mean(), np.std(np.array(scoresphising5))))


0.8799 accuracy with a standard deviation of 0.0039


In [38]:
scoresphising6=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="gini",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising6.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising6).mean(), np.std(np.array(scoresphising6))))

0.7980 accuracy with a standard deviation of 0.0000000000


In [39]:
scoresphising7=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy")
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising7.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.4f" % (np.array(scoresphising7).mean(), np.std(np.array(scoresphising7))))

0.8955 accuracy with a standard deviation of 0.0043


In [40]:
scoresphising8=[]
for i in range(100):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
    dtree_phishing5=DecisionTreeClassifier(criterion="entropy",ccp_alpha = 0.015)
    dtree_phishing5.fit(X_train,y_train)
    y_pred=dtree_phishing5.predict(X_test)
    y_trainpred=dtree_phishing5.predict(X_train)
    accuracy_dtree=accuracy_score(y_test,y_pred)
    scoresphising8.append(accuracy_dtree)
print("%0.4f accuracy with a standard deviation of %0.10f" % (np.array(scoresphising8).mean(), np.std(np.array(scoresphising8))))

0.8522 accuracy with a standard deviation of 0.0000000000
